spring:
  application:
    name: crm-proxy
  main:
    allow-bean-definition-overriding: true

server:
  port: ${PROXY_PORT}

dgs:
  graphql:
    schema-locations:
      - "classpath*:graphql/**/*.graphqls"
    path: /graphql
    federation:
      enabled: true

#SUPPORTTICKETS_URL: http://localhost:8081/api/supporttickets
#CUSTOMERS_URL: http://localhost:8081/api/customers

SUPPORTTICKETS_URL: ${SUPPORTTICKETS_URL}
CUSTOMERS_URL: ${CUSTOMERS_URL}