spring:
  application:
    name: federation-gateway
  main:
    allow-bean-definition-overriding: true

server:
  port: 8083

dgs:
  graphql:
    schema-locations:
      - "classpath*:graphql/**/*.graphqls"
    path: /graphql
    federation:
      enabled: true

SUPPORTTICKETS_URL: http://localhost:8081/api/supporttickets
CUSTOMERS_URL: http://localhost:8081/api/customers